### ISSUE TITLE
add fineweb dataset

### ISSUE THREAD

**Issue by martinjaggi** [epfml/llm-baselines#15]
and fineweb-edu potentially

(fineweb also has a small sample BTW)

**Comment by ath3great** [comment]
users can modify the link like: 

"load_dataset("DKYoon/SlimPajama-6B")" to "load_dataset("fineweb-edu")"

and it will keep work I guess.

**Comment by Andron00e** [comment]
> and fineweb-edu potentially
> 
> (fineweb also has a small sample BTW)

see this commit: 6007a953db4fcb4eb1fa3ac8bacdb2d424d72777
