### ISSUE TITLE
try with pytorch compile for speedup?

### ISSUE THREAD

**Issue by martinjaggi** [epfml/llm-baselines#7]
how much speedup would we observe with the new compile option?
https://pytorch.org/blog/accelerating-large-language-models/

**Comment by mpagli** [comment]
The compilation is already supported:

https://github.com/epfml/llm-baselines/blob/61deef845575cbf41320deb487d038bf825b0533/src/optim/base.py#L24

I'd need to gather better stats but from memory the speedup I observed was around 10% or 20%.
